// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Curry = require("bs-platform/lib/js/curry.js");
var State$ReasonHooksLib = require("../src/State.bs.js");
var Lifecycle$ReasonHooksLib = require("../src/Lifecycle.bs.js");
var ReactHooks = require("@testing-library/react-hooks");

Jest.describe("useDidMount", (function (param) {
        var container = ReactHooks.renderHook((function (param) {
                var match = State$ReasonHooksLib.useCounter(0);
                var inc = match[/* inc */3];
                Lifecycle$ReasonHooksLib.useDidMount((function (param) {
                        Curry._1(inc, /* () */0);
                        return undefined;
                      }));
                return match[/* count */0];
              }), undefined);
        return Jest.test("count is 0", (function (param) {
                      return Jest.Expect[/* toBe */2](1, Jest.Expect[/* expect */0](container.result.current));
                    }));
      }));

/*  Not a pure module */
