// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Curry = require("bs-platform/lib/js/curry.js");
var State$ReasonHooksLib = require("../src/State.bs.js");
var ReactHooksTestingLibrary = require("react-hooks-testing-library");

Jest.describe("useCounter", (function (param) {
        var container = ReactHooksTestingLibrary.renderHook((function () {
                return State$ReasonHooksLib.useCounter(0);
              }));
        Jest.test("counter is 0", (function (param) {
                return Jest.Expect[/* toEqual */12](0, Jest.Expect[/* expect */0](container.result.current[/* counter */0]));
              }));
        Jest.test("counter is 1", (function (param) {
                ReactHooksTestingLibrary.act((function () {
                        return Curry._1(container.result.current[/* set */1], (function (prev) {
                                      return prev + 1 | 0;
                                    }));
                      }));
                return Jest.Expect[/* toEqual */12](1, Jest.Expect[/* expect */0](container.result.current[/* counter */0]));
              }));
        return Jest.test("counter is 2", (function (param) {
                      ReactHooksTestingLibrary.act((function () {
                              return Curry._1(container.result.current[/* set */1], (function (prev) {
                                            return prev + 1 | 0;
                                          }));
                            }));
                      return Jest.Expect[/* toEqual */12](2, Jest.Expect[/* expect */0](container.result.current[/* counter */0]));
                    }));
      }));

Jest.describe("useUndo", (function (param) {
        var result = ReactHooksTestingLibrary.renderHook((function () {
                return State$ReasonHooksLib.useUndo(0);
              })).result;
        Jest.test("(past, present, future) equals ([], 0, [])", (function (param) {
                var current = result.current;
                return Jest.Expect[/* toEqual */12](/* tuple */[
                            /* [] */0,
                            0,
                            /* [] */0
                          ], Jest.Expect[/* expect */0](/* tuple */[
                                current[/* past */3],
                                current[/* present */4],
                                current[/* future */5]
                              ]));
              }));
        Jest.test("(past, present, future) equals ([0], 1, [])", (function (param) {
                ReactHooksTestingLibrary.act((function () {
                        return Curry._1(result.current[/* set */2], (function (prev) {
                                      return prev + 1 | 0;
                                    }));
                      }));
                var current = result.current;
                return Jest.Expect[/* toEqual */12](/* tuple */[
                            /* :: */[
                              0,
                              /* [] */0
                            ],
                            1,
                            /* [] */0
                          ], Jest.Expect[/* expect */0](/* tuple */[
                                current[/* past */3],
                                current[/* present */4],
                                current[/* future */5]
                              ]));
              }));
        Jest.test("(past, present, future) equals ([0, 1], 2, [])", (function (param) {
                ReactHooksTestingLibrary.act((function () {
                        return Curry._1(result.current[/* set */2], (function (prev) {
                                      return prev + 1 | 0;
                                    }));
                      }));
                var current = result.current;
                return Jest.Expect[/* toEqual */12](/* tuple */[
                            /* :: */[
                              0,
                              /* :: */[
                                1,
                                /* [] */0
                              ]
                            ],
                            2,
                            /* [] */0
                          ], Jest.Expect[/* expect */0](/* tuple */[
                                current[/* past */3],
                                current[/* present */4],
                                current[/* future */5]
                              ]));
              }));
        Jest.test("undo: (past, present, future) equals ([0], 1, [2])", (function (param) {
                ReactHooksTestingLibrary.act((function () {
                        return Curry._1(result.current[/* undo */0], /* () */0);
                      }));
                var current = result.current;
                return Jest.Expect[/* toEqual */12](/* tuple */[
                            /* :: */[
                              0,
                              /* [] */0
                            ],
                            1,
                            /* :: */[
                              2,
                              /* [] */0
                            ]
                          ], Jest.Expect[/* expect */0](/* tuple */[
                                current[/* past */3],
                                current[/* present */4],
                                current[/* future */5]
                              ]));
              }));
        return Jest.test("redo: (past, present, future) equals ([0,1], 2, [])", (function (param) {
                      ReactHooksTestingLibrary.act((function () {
                              return Curry._1(result.current[/* redo */1], /* () */0);
                            }));
                      var current = result.current;
                      return Jest.Expect[/* toEqual */12](/* tuple */[
                                  /* :: */[
                                    0,
                                    /* :: */[
                                      1,
                                      /* [] */0
                                    ]
                                  ],
                                  2,
                                  /* [] */0
                                ], Jest.Expect[/* expect */0](/* tuple */[
                                      current[/* past */3],
                                      current[/* present */4],
                                      current[/* future */5]
                                    ]));
                    }));
      }));

/*  Not a pure module */
