// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var State$ReasonHooksLib = require("../src/State.bs.js");
var UseDidUpdateExample$ReasonHooksLib = require("./UseDidUpdateExample.bs.js");
var UseWillUnmoutExample$ReasonHooksLib = require("./UseWillUnmoutExample.bs.js");

function Counter(Props) {
  var match = State$ReasonHooksLib.useCounter(0);
  var set = match[/* set */1];
  var counter = match[/* counter */0];
  var match$1 = counter < 3;
  return React.createElement("div", undefined, "counter: ", String(counter), match$1 ? React.createElement(UseWillUnmoutExample$ReasonHooksLib.make, { }) : null, React.createElement(UseDidUpdateExample$ReasonHooksLib.make, {
                  counter: counter
                }), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(set, (function (prev) {
                                    return prev + 1 | 0;
                                  }));
                    })
                }, "+1"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(set, (function (prev) {
                                    return prev - 1 | 0;
                                  }));
                    })
                }, "-1"));
}

var make = Counter;

exports.make = make;
/* react Not a pure module */
