// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var State$ReasonHooksLib = require("../src/State.bs.js");

function Counter(Props) {
  var match = State$ReasonHooksLib.useCounter(0);
  var set = match[/* set */1];
  return React.createElement("div", undefined, "counter: ", String(match[/* counter */0]), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(set, (function (prev) {
                                    return prev + 1 | 0;
                                  }));
                    })
                }, "+1"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(set, (function (prev) {
                                    return prev - 1 | 0;
                                  }));
                    })
                }, "-1"));
}

var make = Counter;

exports.make = make;
/* react Not a pure module */
