// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var DataEntry$ReasonHooksLib = require("../src/DataEntry.bs.js");

function Field(Props) {
  DataEntry$ReasonHooksLib.useField("hello");
  return React.createElement("div", undefined, React.createElement("input", {
                  type: "text",
                  value: "1",
                  onChange: (function (e) {
                      console.log(e.target.value);
                      return /* () */0;
                    })
                }));
}

var make = Field;

exports.make = make;
/* react Not a pure module */
