// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var DataEntry$ReasonHooksLib = require("../src/DataEntry.bs.js");

function FieldExample(Props) {
  var match = DataEntry$ReasonHooksLib.useField("hello");
  var bind = match[/* bind */3];
  return React.createElement("div", undefined, React.createElement("input", {
                  type: "text",
                  value: bind[/* value */0],
                  onChange: bind[/* onChange */1]
                }));
}

var make = FieldExample;

exports.make = make;
/* react Not a pure module */
