// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var Undo$ReasonHooksLib = require("./Undo.bs.js");
var Counter$ReasonHooksLib = require("./Counter.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement("div", undefined, React.createElement(Undo$ReasonHooksLib.make, { }), React.createElement(Counter$ReasonHooksLib.make, { })), "app");

/*  Not a pure module */
