// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var UseUndo$ReasonHooksLib = require("./UseUndo.bs.js");
var UseHover$ReasonHooksLib = require("./UseHover.bs.js");
var UseCounter$ReasonHooksLib = require("./UseCounter.bs.js");
var UseStateCallBack$ReasonHooksLib = require("./UseStateCallBack.bs.js");
var UseDidMountExample$ReasonHooksLib = require("./UseDidMountExample.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement("div", undefined, React.createElement(UseStateCallBack$ReasonHooksLib.make, { }), React.createElement(UseDidMountExample$ReasonHooksLib.make, { }), React.createElement(UseUndo$ReasonHooksLib.make, { }), React.createElement(UseCounter$ReasonHooksLib.make, { }), React.createElement(UseHover$ReasonHooksLib.make, { })), "app");

/*  Not a pure module */
