// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var State$ReasonHooksLib = require("../src/State.bs.js");
var Lifecycle$ReasonHooksLib = require("../src/Lifecycle.bs.js");

function LifecycleExample(Props) {
  var match = State$ReasonHooksLib.useCounter(0);
  var inc = match[/* inc */3];
  Lifecycle$ReasonHooksLib.useDidMount((function (param) {
          console.log("hello");
          return undefined;
        }));
  return React.createElement("div", {
              onClick: (function (param) {
                  return Curry._1(inc, /* () */0);
                })
            }, String(match[/* counter */0]));
}

var make = LifecycleExample;

exports.make = make;
/* react Not a pure module */
