// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var State$ReasonHooksLib = require("../src/State.bs.js");

function Undo(Props) {
  var match = State$ReasonHooksLib.useUndo(0);
  var set = match[/* set */2];
  var redo = match[/* redo */1];
  var undo = match[/* undo */0];
  return React.createElement("div", undefined, "counter: ", String(match[/* present */4]), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(set, (function (prev) {
                                    return prev + 1 | 0;
                                  }));
                    })
                }, "+1"), React.createElement("button", {
                  disabled: List.length(match[/* past */3]) === 0,
                  onClick: (function (param) {
                      return Curry._1(undo, /* () */0);
                    })
                }, "undo"), React.createElement("button", {
                  disabled: List.length(match[/* future */5]) === 0,
                  onClick: (function (param) {
                      return Curry._1(redo, /* () */0);
                    })
                }, "redo"));
}

var make = Undo;

exports.make = make;
/* react Not a pure module */
