// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Lifecycle$ReasonHooksLib = require("../src/Lifecycle.bs.js");

function UseDidUpdateExample(Props) {
  var count = Props.count;
  Lifecycle$ReasonHooksLib.useDidUpdate((function (param) {
          console.log("did update");
          return undefined;
        }), /* array */[count]);
  return null;
}

var make = UseDidUpdateExample;

exports.make = make;
/* Lifecycle-ReasonHooksLib Not a pure module */
