// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Feedback$ReasonHooksLib = require("../src/Feedback.bs.js");

function UseHover(Props) {
  var match = Feedback$ReasonHooksLib.useHover(/* () */0);
  return React.createElement("div", {
              onMouseEnter: match[/* onMouseEnter */1],
              onMouseLeave: match[/* onMouseLeave */2]
            }, "hovered: " + Pervasives.string_of_bool(match[/* hovered */0]));
}

var make = UseHover;

exports.make = make;
/* react Not a pure module */
