// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var State$ReasonHooksLib = require("../src/State.bs.js");

function UseStateCallBack(Props) {
  var match = State$ReasonHooksLib.useStateCallback(0, (function (param) {
          console.log("cb");
          return undefined;
        }));
  var set = match[/* set */1];
  return React.createElement("div", {
              onClick: (function (param) {
                  return Curry._1(set, (function (prev) {
                                return prev + 1 | 0;
                              }));
                })
            }, String(match[/* state */0]));
}

var make = UseStateCallBack;

exports.make = make;
/* react Not a pure module */
