// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Lifecycle$ReasonHooksLib = require("../src/Lifecycle.bs.js");

function UseWillUnmoutExample(Props) {
  Lifecycle$ReasonHooksLib.useWillUnmount((function (param) {
          console.log("willUnmount");
          return /* () */0;
        }));
  return null;
}

var make = UseWillUnmoutExample;

exports.make = make;
/* Lifecycle-ReasonHooksLib Not a pure module */
