// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

var Field = /* module */[];

function useField(initial) {
  var match = React.useState((function () {
          return initial;
        }));
  var set = match[1];
  var state = match[0];
  return /* record */[
          /* value */state,
          /* set */set,
          /* reset */(function (param) {
              return Curry._1(set, (function (_prev) {
                            return initial;
                          }));
            }),
          /* bind : record */[
            /* value */state,
            /* onChange */(function (e) {
                e.persist();
                return Curry._1(set, (function (_prev) {
                              return e.target.value;
                            }));
              })
          ]
        ];
}

exports.Field = Field;
exports.useField = useField;
/* react Not a pure module */
