// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var State$ReasonHooksLib = require("./State.bs.js");

var useCounter = State$ReasonHooksLib.useCounter;

var useUndo = State$ReasonHooksLib.useUndo;

exports.useCounter = useCounter;
exports.useUndo = useUndo;
/* State-ReasonHooksLib Not a pure module */
