// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var State$ReasonHooksLib = require("./State.bs.js");

var useCounter = State$ReasonHooksLib.useCounter;

var useUndo = State$ReasonHooksLib.useUndo;

var useToggle = State$ReasonHooksLib.useToggle;

var createGlobalStore = State$ReasonHooksLib.createGlobalStore;

exports.useCounter = useCounter;
exports.useUndo = useUndo;
exports.useToggle = useToggle;
exports.createGlobalStore = createGlobalStore;
/* State-ReasonHooksLib Not a pure module */
