// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function useDidMount(f) {
  React.useEffect((function () {
          return Curry._1(f, /* () */0);
        }), /* array */[]);
  return /* () */0;
}

function useWillUnmount(f) {
  React.useEffect((function () {
          return (function (param) {
                    return Curry._1(f, /* () */0);
                  });
        }), /* array */[]);
  return /* () */0;
}

function useDidUpdate(f, conditions) {
  var didMoutRef = React.useRef(false);
  React.useEffect((function () {
          var match = didMoutRef.current;
          if (match) {
            return Curry._1(f, /* () */0);
          } else {
            didMoutRef.current = true;
            return undefined;
          }
        }), conditions);
  return /* () */0;
}

exports.useDidMount = useDidMount;
exports.useWillUnmount = useWillUnmount;
exports.useDidUpdate = useDidUpdate;
/* react Not a pure module */
