// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function createHooksStore(initial) {
  var state = /* record */[/* contents */initial];
  var listeners = /* record */[/* contents : [] */0];
  var setState = function (newState) {
    state[0] = newState;
    return List.iter((function (f) {
                  return Curry._1(f, (function (param) {
                                return state[0];
                              }));
                }), listeners[0]);
  };
  return (function (param) {
      var match = React.useState((function () {
              return state[0];
            }));
      var set = match[1];
      React.useEffect((function () {
              listeners[0] = /* :: */[
                set,
                listeners[0]
              ];
              return (function (param) {
                        listeners[0] = List.filter((function (f) {
                                  return f !== set;
                                }))(listeners[0]);
                        return /* () */0;
                      });
            }), /* array */[]);
      return /* tuple */[
              match[0],
              setState
            ];
    });
}

exports.createHooksStore = createHooksStore;
/* react Not a pure module */
